version: "2"

services:
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     - MYSQL_DATABASE=achat
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
   ports:
      - "3307:3307"
   volumes:
      - db:/var/lib/mysql
 app:
   container_name: spring
   image: youssefksouri/achat
   depends_on:
     - mysqldb
   build: .
   restart: on-failure
   ports:
     - "8089:8089"
   environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achat?useSSL=false",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       "spring.jpa.hibernate.ddl-auto" : "update"}'
   stdin_open: true
   tty: true
    
    
 

volumes:
 db:
